### ISSUE TITLE
How to Make

### ISSUE THREAD

**Issue by lcxone1** [guidoreina/inet_stress_tools#1]
Hi,
i have tried to run "make" but it didn't work. How should I make it?
Thx

**Comment by guidoreina** [comment]
Hi,
This project consists of 4 programs, which you have to compile separately.

```
make -f Makefile.tcp_receiver
make -f Makefile.tcp_sender
make -f Makefile.udp_receiver
make -f Makefile.udp_sender
```

Then, the binaries are under the `bin/` directory.

Thanks for your interest :)
